package uk.ac.ed.inf;

import java.util.ArrayList;
import com.mapbox.geojson.*;

/**
 * This class will write a GeoJson file that illustrates the route of travel for the
 * Drone, it will produce a LineString Geometry and create a FeatureCollection object
 * that will be saved into a GeoJson file that can be viewed in the GeoJson.io website
 *
 * @author Arbnor Bregu s1832263
 * @date 02/12/2021
 * @version 1.0
 */
public class WriteGJson {
    private ArrayList<Drone> points;
    private FeatureCollection featureCollection;

    /**
     * Constructs and initialises a WriteGJson object that will take an ArrayList of Drone objects
     * and construct a LineString geometry to put into a FeatureCollection
     * @param points is an ArrayList of Longlat objects
     */
    WriteGJson(ArrayList<Drone> points) {
        this.points = points;
        ArrayList<Point> listOfPoints = new ArrayList<>();
        for (Drone point : points) {
            listOfPoints.add(Point.fromLngLat(point.getLongitude(), point.getLatitude()));
        }
        LineString lineString = LineString.fromLngLats(listOfPoints);
        Geometry geometryOfLineString = (Geometry) lineString;
        Feature feature = Feature.fromGeometry(geometryOfLineString);
        this.featureCollection = FeatureCollection.fromFeature(feature);
    }

    /**
     * This function will turn the FeatureCollection object generated by WriteGJson
     * into a Json string.
     * @return a String object that is the FeatureColletion object in the Json format.
     */
    public String toJson() {return featureCollection.toJson();}
}
